audio:
  # Recording settings
  format: pyaudio.paInt16
  device_id: 0
  sample_size_in_bytes: 2
  channels: 1
  sr: 16000
  frame_size_in_bytes: 4096 # Maybe this would be better represented in seconds
  feature_buffer_size_in_bytes: 8192
  database_filename: "recordings.db"
  stats_filename: "stats.csv"

vad:
  vad_decision_threshold: 0.1 # Threshold to identify noise frames
